name = "portfolio"
compatibility_date = "2024-04-22"

[build]
command = "npm run build"
cwd = "."
upload = { format = "directory", dir = "public" }

[env.production]
pages_build_output_dir = "./public"
