import backgroundSprLarge from '~/assets/spr-background-large.jpg';
import backgroundSprPlaceholder from '~/assets/spr-background-placeholder.jpg';
import backgroundSpr from '~/assets/spr-background.jpg';
import imageSynthosLarge from '~/assets/synthos-large.jpg';
import imageSynthosPlaceholder from '~/assets/synthos-placeholder.jpg';
import imageSynthos from '~/assets/synthos.jpg';
import { Footer } from '~/components/footer';
import { Image } from '~/components/image';
import { Link } from '~/components/link';
import { ThemeProvider, useTheme } from '~/components/theme-provider';
import {
  ProjectBackground,
  ProjectContainer,
  ProjectHeader,
  ProjectImage,
  ProjectSection,
  ProjectSectionColumns,
  ProjectSectionContent,
  ProjectSectionHeading,
  ProjectSectionText,
  ProjectTextRow,
} from '~/layouts/project';
import { baseMeta } from '~/utils/meta';
import { media } from '~/utils/style';
import styles from './synthos.module.css';

const title = 'SynthOS - Synthetic Data Validation Platform';
const description =
  'The first synthetic data validation platform with model collapse detection, built at Genovo Technologies (NVIDIA Inception). Multi-scale cascade validation using 15+ proxy models predicting collapse with 90%+ accuracy before $100M training runs.';
const roles = [
  'Founder & CEO',
  'Product Architect',
  'ML Engineering Lead',
  'Infrastructure Design',
];

export const meta = () => {
  return baseMeta({ title, description, prefix: 'Projects' });
};

export const SynthOS = () => {
  const { theme } = useTheme();
  const isDark = theme === 'dark';

  return (
    <>
      <ProjectContainer>
        <ProjectBackground
          opacity={isDark ? 0.5 : 0.8}
          src={backgroundSpr}
          srcSet={`${backgroundSpr} 1080w, ${backgroundSprLarge} 2160w`}
          placeholder={backgroundSprPlaceholder}
        />
        <ProjectHeader
          title={title}
          description={description}
          url="https://genovotech.com"
          roles={roles}
        />
        <ProjectSection padding="top">
          <ProjectSectionContent>
            <ProjectImage
              raised
              key={theme}
              srcSet={`${imageSynthos} 1280w, ${imageSynthosLarge} 2560w`}
              width={1280}
              height={800}
              placeholder={imageSynthosPlaceholder}
              sizes={`(max-width: ${media.mobile}px) 100vw, (max-width: ${media.tablet}px) 800px, 1000px`}
              alt="SynthOS validation dashboard showing model collapse detection and cascade validation results"
            />
          </ProjectSectionContent>
        </ProjectSection>
        <ProjectSection>
          <ProjectTextRow>
            <ProjectSectionHeading>The problem</ProjectSectionHeading>
            <ProjectSectionText>
              As AI labs increasingly rely on synthetic data to augment training datasets, a critical 
              risk has emerged: model collapse. When models are trained on synthetic data generated by 
              other models, subtle distribution shifts compound across generations, eventually degrading 
              model quality catastrophically. With training runs costing $10M-$100M+, discovering data 
              quality issues post-training represents an existential financial risk for AI companies.
            </ProjectSectionText>
          </ProjectTextRow>
        </ProjectSection>
        <ProjectSection>
          <ProjectSectionContent>
            <ProjectTextRow>
              <ProjectSectionHeading>The solution</ProjectSectionHeading>
              <ProjectSectionText>
                SynthOS is the first synthetic data validation platform specifically designed to detect 
                and predict model collapse before expensive training runs begin. The platform implements 
                multi-scale cascade validation using 15+ proxy models ranging from 1M to 500M parameters, 
                enabling rapid assessment of synthetic data quality at a fraction of the cost of full-scale 
                training.
              </ProjectSectionText>
              <ProjectSectionText>
                The system provides performance warranties backed by our validation methodology — 
                predicting model collapse with 90%+ accuracy. Our performance-based pricing model 
                captures 30% of the cost savings we generate for clients, aligning our incentives 
                with customer outcomes. The product was successfully pivoted through 3 lifecycles 
                based on YCombinator feedback loops.
              </ProjectSectionText>
            </ProjectTextRow>
          </ProjectSectionContent>
        </ProjectSection>
        <ProjectSection>
          <ProjectSectionColumns>
            <ProjectSectionContent>
              <ProjectSectionHeading>Technical architecture</ProjectSectionHeading>
              <ProjectSectionText>
                SynthOS is built on a sophisticated ML pipeline that validates synthetic data across 
                multiple dimensions — statistical fidelity, distribution drift, diversity indices, and 
                collapse probability. The cascade architecture progressively tests data against larger 
                proxy models, catching issues early at minimal compute cost.
              </ProjectSectionText>
              <ProjectSectionText>
                Key technical components:
              </ProjectSectionText>
              <ul>
                <li>Multi-scale cascade validation (1M → 500M param proxy models)</li>
                <li>Model collapse detection with 90%+ prediction accuracy</li>
                <li>Distribution drift monitoring and early warning system</li>
                <li>Statistical fidelity scoring across 50+ metrics</li>
                <li>Performance warranty engine with confidence intervals</li>
                <li>AWS infrastructure (SageMaker, EC2, S3) with Kubernetes orchestration</li>
              </ul>
            </ProjectSectionContent>
            <ProjectSectionContent>
              <ProjectSectionHeading>Business impact</ProjectSectionHeading>
              <ProjectSectionText>
                Genovo Technologies was selected for NVIDIA's exclusive Inception Program for 
                AI/Data infrastructure advancements, validating our technical approach. The 
                platform reduces computational complexity 10× compared to naive validation 
                approaches — validating datasets that would take weeks to test through full 
                training runs in hours.
              </ProjectSectionText>
              <ProjectSectionText>
                As Founder & CEO, I lead an 11-person team across ML engineering, backend 
                infrastructure, and DevOps — with a CTO/Co-founder handling Go, Rust, Python, 
                and React-based engineering. The company has secured pilot programs with enterprise 
                AI labs, with a performance-based pricing model that directly demonstrates value 
                to customers. Built as a Delaware C-Corp with international operations.
              </ProjectSectionText>
            </ProjectSectionContent>
          </ProjectSectionColumns>
        </ProjectSection>
        <ProjectSection>
          <ProjectSectionContent>
            <ProjectTextRow>
              <ProjectSectionHeading>Technology & roadmap</ProjectSectionHeading>
              <ProjectSectionText>
                The SynthOS technical stack includes Python, PyTorch, Rust, AWS (SageMaker, EC2, S3), 
                Docker, and Kubernetes. SynthOS feeds into Genovo's broader SCOS vision — a Synthetic 
                Cognition Operating System providing a unified, predictive, self-optimizing intelligent 
                network across manufacturing, energy grids, smart cities, healthcare, and supply chains. 
                Our immediate roadmap includes multimodal data support, continuous monitoring for 
                production pipelines, and integrations with major ML platforms.
              </ProjectSectionText>
            </ProjectTextRow>
          </ProjectSectionContent>
        </ProjectSection>
      </ProjectContainer>
      <Footer />
    </>
  );
}; 
